app:
  port: "8000"
  domain: "http://localhost:8000"

jwt:
  key: "90986945701389"
  issuer: "marvel"
  duration: "10080"
  refresh_duration: "43200"

mysql:
  host: "127.0.0.1"
  database: "marvel_project"
  password: "sapi"
  port: "3306"
  user: "root"

redis:
  max_idle: "10"
  max_active: "100"
  address: "127.0.0.1"
  port: "6379"
  password: "makan_enak"

mongodb:
  address: "127.0.0.1"
  database: "marvel_project"
  port: "27017"
  user: "mongoadmin"
  password: "sapi"
