app:
  port: "8000"
  domain: "http://localhost:8000"

jwt:
  key: "pnp-token"
  issuer: "parknparcel"
  duration: "10080"
  refresh_duration: "43200"

mysql:
  host: "127.0.0.1"
  database: "pnp_middleware"
  password: "i5q8}sZUIXnt"
  port: "3306"
  user: "parknpar_userdb"

mysql-cainiao:
  host: "127.0.0.1"
  database: "cainiao_middleware"
  password: "i5q8}sZUIXnt"
  port: "3306"
  user: "parknpar_userdb"

redis:
  max_idle: "10"
  max_active: "100"
  address: "127.0.0.1"
  port: "6379"
  password: ""

mongodb:
  address: "34.143.243.76"
  database: "pnp-middleware-stage"
  port: "27017"
  user: "parknparceluser"
  password: "gangan87"